name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:

  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

  build:
    name: iOS Build
    needs: create_release
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
    steps:

    - name: Check out repo
      uses: actions/checkout@v2

    - name: Download sdkboxt
      run: curl https://raw.githubusercontent.com/sdkbox/storage/master/sdkboxtools/sdkboxt -o sdkboxt && chmod +x ./sdkboxt

    - name: Build
      run: ./sdkboxt -cmd build

    - name: Package
      run: ./sdkboxt -cmd package

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: AppsFlyer.zip
        asset_name: AppsFlyer.zip
        asset_content_type: application/octet-stream


